#server begin
server:
  port: 8083
#server end


#datasource begin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#datasource end

  redis:
    host: 192.168.126.155
    port: 6379
    password: xyfei

#mybatis-plus begin
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus end

logging:
  level:
    cn.jay.repository: trace
  config: classpath:log4j.properties

